path = require('path')
{print} = require 'util'
{spawn} = require 'child_process'


npmBinDir = path.join('node_modules', '.bin')
coffeeSourceDir = '.'
coffeeBuildDir = path.join('..', '..', 'static', 'devilry_examiner')
coffeeCmd = path.join(npmBinDir, 'coffee')


coffee = (options, callbacks={}) ->
    coffee = spawn(coffeeCmd, options)
    coffee.stderr.on 'data', (data) ->
        process.stderr.write data.toString()
    coffee.stdout.on 'data', (data) ->
        print data.toString()
    coffee.on 'exit', (code) ->
        if code == 0
            callbacks.onSuccess?()
        else
            callbacks.onError?()

coffeeBuildAll = ->
    coffee ['-c', '-o', coffeeBuildDir, coffeeSourceDir],
        onError: (code) ->
            console.error 'Build FAILED with exit-code:', code
        onSuccess: ->
            console.log 'Build successful'

task 'coffeeBuild', 'Build the coffeescript sources.', ->
    coffeeBuildAll()

task 'coffeeWatch', 'Watch the coffeescript sources for changes, and rebuild automatically.', ->
    coffee(['-o', coffeeBuildDir, '-cw', coffeeSourceDir])

